# ingore_errors, failed_when 
---
- name: error handling using ignore_error module
  hosts: localhost
  gather_facts: no
  tasks:
    - shell: 'ls /home'
      register: home_out
    - debug: var=home_out.rc
    - shell: 'docker ps'
      register: docker_ps_out
      ignore_errors: true
    - debug: var=docker_ps_out.rc
    - shell: 'curl -s  -o /dev/null -w "%{http_code}" http://10.0.19.10/ --connect-timeout 5'
      register: curl_out
      failed_when: curl_out.rc!=0
    - debug:
        msg: "executed after failed_when"









